import { StateGraph } from "@langchain/langgraph";
import { HiltStatus } from "./state";
declare const workflow: StateGraph<{
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}, import("@langchain/langgraph").StateType<{
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}>, import("@langchain/langgraph").UpdateType<{
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}>, "search" | "synthesize" | "__start__" | "plan_research" | "await_approval" | "generate_ideas", {
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}, {
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}, import("@langchain/langgraph").StateDefinition, {
    plan_research: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    search: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    synthesize: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    await_approval: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    generate_ideas: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
}, unknown, unknown>;
export declare const graph: import("@langchain/langgraph").CompiledStateGraph<{
    userPrompt: string;
    threadId: string;
    refinementFeedback: string | null;
    researchPlan: import("./state").ResearchPlanState | null;
    searchResults: import("./state").SearchResultState[];
    trends: import("./state").TrendState[];
    hitlStatus: HiltStatus | null;
    ideas: import("./state").IdeaState[];
    brandContext: import("./state").BrandContextState;
    currentStep: import("../schema").ThreadStatusEnum;
    error: string | null;
    messages: import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[];
}, {
    userPrompt?: string | undefined;
    threadId?: string | undefined;
    refinementFeedback?: string | null | undefined;
    researchPlan?: import("./state").ResearchPlanState | null | undefined;
    searchResults?: import("./state").SearchResultState[] | undefined;
    trends?: import("./state").TrendState[] | undefined;
    hitlStatus?: HiltStatus | null | undefined;
    ideas?: import("./state").IdeaState[] | undefined;
    brandContext?: import("./state").BrandContextState | undefined;
    currentStep?: import("../schema").ThreadStatusEnum | undefined;
    error?: string | null | undefined;
    messages?: import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[] | undefined;
}, "search" | "synthesize" | "__start__" | "plan_research" | "await_approval" | "generate_ideas", {
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}, {
    userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
    refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
    searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
    trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
    hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
    ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
    brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
    currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
    error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
    messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
}, import("@langchain/langgraph").StateDefinition, {
    plan_research: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    search: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    synthesize: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    await_approval: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
    generate_ideas: Partial<import("@langchain/langgraph").StateType<{
        userPrompt: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        threadId: import("@langchain/langgraph").BinaryOperatorAggregate<string, string>;
        refinementFeedback: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        researchPlan: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").ResearchPlanState | null, import("./state").ResearchPlanState | null>;
        searchResults: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").SearchResultState[], import("./state").SearchResultState[]>;
        trends: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").TrendState[], import("./state").TrendState[]>;
        hitlStatus: import("@langchain/langgraph").BinaryOperatorAggregate<HiltStatus | null, HiltStatus | null>;
        ideas: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").IdeaState[], import("./state").IdeaState[]>;
        brandContext: import("@langchain/langgraph").BinaryOperatorAggregate<import("./state").BrandContextState, import("./state").BrandContextState>;
        currentStep: import("@langchain/langgraph").BinaryOperatorAggregate<import("../schema").ThreadStatusEnum, import("../schema").ThreadStatusEnum>;
        error: import("@langchain/langgraph").BinaryOperatorAggregate<string | null, string | null>;
        messages: import("@langchain/langgraph").BinaryOperatorAggregate<import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[], import("@langchain/core/messages").BaseMessage<import("@langchain/core/messages").MessageStructure<import("@langchain/core/messages").MessageToolSet>, import("@langchain/core/messages").MessageType>[]>;
    }>>;
}, unknown, unknown>;
export { workflow };
